apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: kafka-ssl-sink-pipe
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: kafka-ssl-sink
    properties:
      bootstrapServers: "The Brokers"
      sslKeyPassword: "The SSL Key Password"
      sslKeystoreLocation: "The SSL Keystore Location"
      sslKeystorePassword: "The SSL Keystore Password"
      sslTruststoreLocation: "The SSL Truststore Location"
      topic: "The Topic Names"
  