name: Publish Website
on:
  push:
    branches:
      - main
      - release-2.3.x
jobs:
  publish-pages:
    runs-on: ubuntu-latest
    if: github.repository == 'openshift-integration/kamelet-catalog'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release-2.3.x
      - name: Build
        run: |
          cd docs
          yarn install
          yarn build
          touch build/site/.nojekyll

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build/site
