name: Publish Website
on:
  push:
    branches:
    - kamelet-catalog-1.4
    - master
jobs:
  publish-pages:
    runs-on: ubuntu-latest
    if: github.repository == 'openshift-integration/kamelet-catalog'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: kamelet-catalog-1.4
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build
        run: |
          cd docs
          yarn install
          yarn build
          touch build/site/.nojekyll

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build/site
