name: Validate

on:
  pull_request:
    branches:
      - main
      - release-2.3.x
    paths-ignore:
      - '**.adoc'
      - 'KEYS'
      - 'LICENSE'
      - 'NOTICE'
  push:
    branches:
      - main
      - release-2.3.x
    paths-ignore:
      - '**.adoc'
      - 'KEYS'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.20.x
    - name: Run Validator
      run: |
        echo "Running Kamelet validator..."

        cd script/validator
        go run . ../../
